
package services.ecentric.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import services.ecentric.com.xsd.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicesPortType", targetNamespace = "http://services/ecentric/com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicesPortType {


    /**
     * 
     * @param timeStamp
     * @param encPID
     * @param encSessionKey
     * @param eKYCOption
     * @param uidNum
     * @param agencyCode
     * @param encHmac
     * @param agencyName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAadhaarDemographicDataBySRDHSecuredeKYC")
    @WebResult(targetNamespace = "http://services/ecentric/com/xsd")
    @RequestWrapper(localName = "getAadhaarDemographicDataBySRDHSecuredeKYC", targetNamespace = "http://services/ecentric/com/xsd", className = "services.ecentric.com.xsd.GetAadhaarDemographicDataBySRDHSecuredeKYC")
    @ResponseWrapper(localName = "getAadhaarDemographicDataBySRDHSecuredeKYCResponse", targetNamespace = "http://services/ecentric/com/xsd", className = "services.ecentric.com.xsd.GetAadhaarDemographicDataBySRDHSecuredeKYCResponse")
    public String getAadhaarDemographicDataBySRDHSecuredeKYC(
        @WebParam(name = "encPID", targetNamespace = "http://services/ecentric/com/xsd")
        byte[] encPID,
        @WebParam(name = "encSessionKey", targetNamespace = "http://services/ecentric/com/xsd")
        byte[] encSessionKey,
        @WebParam(name = "encHmac", targetNamespace = "http://services/ecentric/com/xsd")
        byte[] encHmac,
        @WebParam(name = "uidNum", targetNamespace = "http://services/ecentric/com/xsd")
        String uidNum,
        @WebParam(name = "agencyName", targetNamespace = "http://services/ecentric/com/xsd")
        String agencyName,
        @WebParam(name = "agencyCode", targetNamespace = "http://services/ecentric/com/xsd")
        String agencyCode,
        @WebParam(name = "eKYCOption", targetNamespace = "http://services/ecentric/com/xsd")
        String eKYCOption,
        @WebParam(name = "TimeStamp", targetNamespace = "http://services/ecentric/com/xsd")
        String timeStamp);

}
