
package authentication.org;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.authentication.xsd.BFDBiometricRequest;
import org.authentication.xsd.FingerPositionTemplateModel;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicesPortType", targetNamespace = "http://authentication/org/")
@XmlSeeAlso({
    authentication.org.xsd.ObjectFactory.class,
    org.authentication.xsd.ObjectFactory.class
})
public interface ServicesPortType {


    /**
     * 
     * @param eidNum
     * @param uidNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:srdhUidVerification")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "srdhUidVerification", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.SrdhUidVerification")
    @ResponseWrapper(localName = "srdhUidVerificationResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.SrdhUidVerificationResponse")
    public String srdhUidVerification(
        @WebParam(name = "uid_num", targetNamespace = "http://authentication/org/xsd")
        String uidNum,
        @WebParam(name = "eid_num", targetNamespace = "http://authentication/org/xsd")
        String eidNum);

    /**
     * 
     * @param certificateIdentifier
     * @param encryptedPid
     * @param encSessionKey
     * @param dataType
     * @param uidNum
     * @param agencyCode
     * @param agencyName
     * @param encHmac
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PIDBlockIrisAuthService", action = "urn:PIDBlockIrisAuthService")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "PIDBlockIrisAuthService", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.PIDBlockIrisAuthService")
    @ResponseWrapper(localName = "PIDBlockIrisAuthServiceResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.PIDBlockIrisAuthServiceResponse")
    public String pidBlockIrisAuthService(
        @WebParam(name = "uid_num", targetNamespace = "http://authentication/org/xsd")
        String uidNum,
        @WebParam(name = "agency_name", targetNamespace = "http://authentication/org/xsd")
        String agencyName,
        @WebParam(name = "agency_code", targetNamespace = "http://authentication/org/xsd")
        String agencyCode,
        @WebParam(name = "encryptedPid", targetNamespace = "http://authentication/org/xsd")
        String encryptedPid,
        @WebParam(name = "encSessionKey", targetNamespace = "http://authentication/org/xsd")
        String encSessionKey,
        @WebParam(name = "encHmac", targetNamespace = "http://authentication/org/xsd")
        String encHmac,
        @WebParam(name = "certificateIdentifier", targetNamespace = "http://authentication/org/xsd")
        String certificateIdentifier,
        @WebParam(name = "dataType", targetNamespace = "http://authentication/org/xsd")
        String dataType);

    /**
     * 
     * @param studentId
     * @param dmhCode
     * @param udc
     * @param fingerPosition
     * @param binaryTemplate
     * @param uidNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:scholorBiometricAuthService")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "scholorBiometricAuthService", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.ScholorBiometricAuthService")
    @ResponseWrapper(localName = "scholorBiometricAuthServiceResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.ScholorBiometricAuthServiceResponse")
    public String scholorBiometricAuthService(
        @WebParam(name = "studentId", targetNamespace = "http://authentication/org/xsd")
        String studentId,
        @WebParam(name = "dmhCode", targetNamespace = "http://authentication/org/xsd")
        String dmhCode,
        @WebParam(name = "uid_num", targetNamespace = "http://authentication/org/xsd")
        String uidNum,
        @WebParam(name = "Binary_template", targetNamespace = "http://authentication/org/xsd")
        String binaryTemplate,
        @WebParam(name = "Finger_position", targetNamespace = "http://authentication/org/xsd")
        String fingerPosition,
        @WebParam(name = "udc", targetNamespace = "http://authentication/org/xsd")
        String udc);

    /**
     * 
     * @param udc
     * @param fingerPosition
     * @param binaryTemplate
     * @param uidNum
     * @param agencyCode
     * @param agencyName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BiometricAuthService", action = "urn:BiometricAuthService")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "BiometricAuthService", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.BiometricAuthService")
    @ResponseWrapper(localName = "BiometricAuthServiceResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.BiometricAuthServiceResponse")
    public String biometricAuthService(
        @WebParam(name = "uid_num", targetNamespace = "http://authentication/org/xsd")
        String uidNum,
        @WebParam(name = "Binary_template", targetNamespace = "http://authentication/org/xsd")
        String binaryTemplate,
        @WebParam(name = "Finger_position", targetNamespace = "http://authentication/org/xsd")
        String fingerPosition,
        @WebParam(name = "UDC", targetNamespace = "http://authentication/org/xsd")
        String udc,
        @WebParam(name = "agency_name", targetNamespace = "http://authentication/org/xsd")
        String agencyName,
        @WebParam(name = "agency_code", targetNamespace = "http://authentication/org/xsd")
        String agencyCode);

    /**
     * 
     * @param gender
     * @param beneficiaryName
     * @param uidNum
     * @param agencyCode
     * @param agencyName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DemoAuthenticationservice", action = "urn:DemoAuthenticationservice")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "DemoAuthenticationservice", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.DemoAuthenticationservice")
    @ResponseWrapper(localName = "DemoAuthenticationserviceResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.DemoAuthenticationserviceResponse")
    public String demoAuthenticationservice(
        @WebParam(name = "uid_num", targetNamespace = "http://authentication/org/xsd")
        String uidNum,
        @WebParam(name = "beneficiary_name", targetNamespace = "http://authentication/org/xsd")
        String beneficiaryName,
        @WebParam(name = "agency_name", targetNamespace = "http://authentication/org/xsd")
        String agencyName,
        @WebParam(name = "agency_code", targetNamespace = "http://authentication/org/xsd")
        String agencyCode,
        @WebParam(name = "gender", targetNamespace = "http://authentication/org/xsd")
        String gender);

    /**
     * 
     * @param studentId
     * @param uid
     * @param dmhCode
     * @param fingerPositionTemplateModel
     * @param udc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:scholorBFDBiometricAuthService")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "scholorBFDBiometricAuthService", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.ScholorBFDBiometricAuthService")
    @ResponseWrapper(localName = "scholorBFDBiometricAuthServiceResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.ScholorBFDBiometricAuthServiceResponse")
    public String scholorBFDBiometricAuthService(
        @WebParam(name = "uid", targetNamespace = "http://authentication/org/xsd")
        String uid,
        @WebParam(name = "studentId", targetNamespace = "http://authentication/org/xsd")
        String studentId,
        @WebParam(name = "dmhCode", targetNamespace = "http://authentication/org/xsd")
        String dmhCode,
        @WebParam(name = "fingerPositionTemplateModel", targetNamespace = "http://authentication/org/xsd")
        List<FingerPositionTemplateModel> fingerPositionTemplateModel,
        @WebParam(name = "udc", targetNamespace = "http://authentication/org/xsd")
        String udc);

    /**
     * 
     * @param irisPosition
     * @param udc
     * @param binaryTemplate
     * @param uidNum
     * @param agencyCode
     * @param agencyName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IRISBiometricAuthService", action = "urn:IRISBiometricAuthService")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "IRISBiometricAuthService", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.IRISBiometricAuthService")
    @ResponseWrapper(localName = "IRISBiometricAuthServiceResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.IRISBiometricAuthServiceResponse")
    public String irisBiometricAuthService(
        @WebParam(name = "uid_num", targetNamespace = "http://authentication/org/xsd")
        String uidNum,
        @WebParam(name = "Binary_template", targetNamespace = "http://authentication/org/xsd")
        String binaryTemplate,
        @WebParam(name = "Iris_position", targetNamespace = "http://authentication/org/xsd")
        String irisPosition,
        @WebParam(name = "UDC", targetNamespace = "http://authentication/org/xsd")
        String udc,
        @WebParam(name = "agency_name", targetNamespace = "http://authentication/org/xsd")
        String agencyName,
        @WebParam(name = "agency_code", targetNamespace = "http://authentication/org/xsd")
        String agencyCode);

    /**
     * 
     * @param certificateIdentifier
     * @param encryptedPid
     * @param encSessionKey
     * @param dataType
     * @param uidNum
     * @param agencyCode
     * @param agencyName
     * @param encHmac
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PIDBlockFingerPrintAuthService", action = "urn:PIDBlockFingerPrintAuthService")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "PIDBlockFingerPrintAuthService", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.PIDBlockFingerPrintAuthService")
    @ResponseWrapper(localName = "PIDBlockFingerPrintAuthServiceResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.PIDBlockFingerPrintAuthServiceResponse")
    public String pidBlockFingerPrintAuthService(
        @WebParam(name = "uid_num", targetNamespace = "http://authentication/org/xsd")
        String uidNum,
        @WebParam(name = "agency_name", targetNamespace = "http://authentication/org/xsd")
        String agencyName,
        @WebParam(name = "agency_code", targetNamespace = "http://authentication/org/xsd")
        String agencyCode,
        @WebParam(name = "encryptedPid", targetNamespace = "http://authentication/org/xsd")
        String encryptedPid,
        @WebParam(name = "encSessionKey", targetNamespace = "http://authentication/org/xsd")
        String encSessionKey,
        @WebParam(name = "encHmac", targetNamespace = "http://authentication/org/xsd")
        String encHmac,
        @WebParam(name = "certificateIdentifier", targetNamespace = "http://authentication/org/xsd")
        String certificateIdentifier,
        @WebParam(name = "dataType", targetNamespace = "http://authentication/org/xsd")
        String dataType);

    /**
     * 
     * @param sessionKey
     * @param udc
     * @param fingerPosition
     * @param binaryTemplate
     * @param uidNum
     * @param agencyCode
     * @param agencyName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SecuredBiometricAuthService", action = "urn:SecuredBiometricAuthService")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "SecuredBiometricAuthService", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.SecuredBiometricAuthService")
    @ResponseWrapper(localName = "SecuredBiometricAuthServiceResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.SecuredBiometricAuthServiceResponse")
    public String securedBiometricAuthService(
        @WebParam(name = "uid_num", targetNamespace = "http://authentication/org/xsd")
        String uidNum,
        @WebParam(name = "Binary_template", targetNamespace = "http://authentication/org/xsd")
        String binaryTemplate,
        @WebParam(name = "Finger_position", targetNamespace = "http://authentication/org/xsd")
        String fingerPosition,
        @WebParam(name = "UDC", targetNamespace = "http://authentication/org/xsd")
        String udc,
        @WebParam(name = "agency_name", targetNamespace = "http://authentication/org/xsd")
        String agencyName,
        @WebParam(name = "agency_code", targetNamespace = "http://authentication/org/xsd")
        String agencyCode,
        @WebParam(name = "sessionKey", targetNamespace = "http://authentication/org/xsd")
        String sessionKey);

    /**
     * 
     * @param bfdBiometricRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BFDBiometricAuthService", action = "urn:BFDBiometricAuthService")
    @WebResult(targetNamespace = "http://authentication/org/xsd")
    @RequestWrapper(localName = "BFDBiometricAuthService", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.BFDBiometricAuthService")
    @ResponseWrapper(localName = "BFDBiometricAuthServiceResponse", targetNamespace = "http://authentication/org/xsd", className = "authentication.org.xsd.BFDBiometricAuthServiceResponse")
    public String bfdBiometricAuthService(
        @WebParam(name = "bfdBiometricRequest", targetNamespace = "http://authentication/org/xsd")
        BFDBiometricRequest bfdBiometricRequest);

}
